queue_rules:
  - name: default
    conditions:
      - check-success=all
      - label=automerge
      - base=main
      - "#changes-requested-reviews-by=0"
      - "#approved-reviews-by>=1"
      
pull_request_rules:
  - name: automatic merge when CI passes on main
    conditions:
      - check-success=all
      - label=automerge
      - base=main
      - "#changes-requested-reviews-by=0"
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
        method: squash

  - name: automatic approval
    conditions:
      - author~=^wirednkod$
    actions:
      review:
        type: APPROVE
        message: Automatically approving wirednkod's pull requests. This auto-approval will be removed once more maintainers are active.
