queue_rules:
  - name: default
    queue_conditions:
      - check-success=all
      - label=automerge
      - base=main
      - "#changes-requested-reviews-by=0"
      - "#approved-reviews-by>=1"
    merge_conditions:
      - check-success=all
      - label=automerge
      - base=main
      - "#changes-requested-reviews-by=0"
      - "#approved-reviews-by>=1"
    merge_method: squash

pull_request_rules:
  - name: automatic merge when CI passes on main
    conditions: []
    actions:
      queue:
