packages:
  - packages/*
  - projects/*
  - zombienet-tests
  - examples/*

catalog:
  typescript: "5.6.2"

catalogs:
  polkadot-api:
    "polkadot-api": "^1.4.1"
    "@polkadot-api/codegen": "~0.12.3"
    "@polkadot-api/metadata-builders": "~0.8.1"
    "@polkadot-api/observable-client": "~0.5.8"
    "@polkadot-api/substrate-bindings": "~0.9.1"
    "@polkadot-api/substrate-client": "~0.2.2"
    "@polkadot-api/json-rpc-provider": "~0.0.4"
    "@polkadot-api/polkadot-signer": "~0.1.6"
    "@polkadot-api/utils": "~0.1.2"
    "@polkadot-api/json-rpc-provider-proxy": "~0.2.3"
    "@polkadot-api/metadata-compatibility": "~0.1.8"
    "@polkadot-api/signer": "~0.1.7"
    "@polkadot-api/view-builder": "~0.3.8"
