[settings]
timeout = 120000

[relaychain]
default_image = "parity/polkadot:latest"
chain = "dev"
default_command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  extra_args = [ "--alice" ]

  [[relaychain.nodes]]
  name = "bob"
  extra_args = [ "--bob" ]
