[settings]
timeout = 240000

[relaychain]
default_image = "parity/polkadot:latest"
chain = "dev"
default_command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true
  extra_args = [ "--alice" ]

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  extra_args = [ "--bob" ]
