name: Publish Package
description: Publish Package to NPM
inputs:
  token:
    description: NPM Token
    required: true
  package-directory:
    description: Package directory
    required: true
outputs:
  type:
    description: Semver release type, `initial` if first release, `different` if other change, or empty if no release.
    value: ${{ steps.publish.outputs.type }}
runs:
  using: composite
  steps:
    - name: Pack
      run: pnpm pack && mv *.tgz package.tgz
      shell: bash
      working-directory: ${{ inputs.package-directory }}
    - uses: actions/upload-artifact@v3
      with:
        name: package
        working-directory: ${{ inputs.package-directory }}
        path: "package.tgz"
    - name: Publish
      id: publish
      uses: octokit/request-action@v2.x
      with:
        route: POST /repos/paritytech/npm_publish_automation/actions/workflows/publish.yml/dispatches
        ref: main
        inputs: '${{ format(''{{ "repo": "{0}", "run_id": "{1}" }}'', github.repository, github.run_id) }}'
      env:
        GITHUB_TOKEN: ${{ secrets.NPM_PUBLISH_AUTOMATION_TOKEN }}
