[settings]
timeout = 240000

[relaychain]
default_image = "parity/polkadot:latest"
chain = "rococo-local"
default_command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true
  add_to_bootnodes = true
