name: Bundlers integration test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:    
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        path: './projects/bundlers'
    - run: yarn install
    - run: yarn run testbuild
    
  all:
    # This dummy job depends on all the mandatory checks. It succeeds if and only if all CI checks
    # are successful.
    needs: [build]
    runs-on: ubuntu-latest
    steps:
     - run: echo Success
