name: Deploy

on:
  workflow_dispatch:

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - run: |
          git remote set-branches origin gh-pages
          git fetch --depth 1 origin gh-pages
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install --immutable
      - name: Deploy
        run: yarn run deploy
