name: Upload extension artifacts

on:
  push:
    branches: [ main ]

jobs:
  upload-extension-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Cache turbo build setup
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-18.x-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-18.x-build-
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm
      - uses: actions/upload-artifact@v4
        with:
          name: substrate-connect-extension-source-code
          path: ./projects/extension
      - run: pnpm install
      - run: pnpm turbo build --cache-dir=.turbo
      - run: pnpm --filter @substrate/extension build:firefox
      - uses: actions/upload-artifact@v4
        with:
          name: substrate-connect-extension-mv3-firefox
          path: ./projects/extension/dist
      - run: pnpm --filter @substrate/extension build:chrome
      - uses: actions/upload-artifact@v4
        with:
          name: substrate-connect-extension-mv3-chrome
          path: ./projects/extension/dist

  all:
    # This dummy job depends on all the mandatory checks. It succeeds if and only if all CI checks
    # are successful.
    needs: [upload-extension-artifacts]
    runs-on: ubuntu-latest
    steps:
     - run: echo Success
